services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - auth-service
      - analytics-service
    networks:
      - tourism-pulse-nz-network

  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    networks:
      - tourism-pulse-nz-network

  analytics-service:
    build:
      context: ./backend/analytics-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
    networks:
      - tourism-pulse-nz-network

networks:
  tourism-pulse-nz-network:
    driver: bridge
